#!/bin/sh

version=1.0.2

clean()
{
    git rm -rf Dockerfile root
}

build()
(
    # To better understand how this works (or how to make this work)
    # see https://github.com/devexp-db/cont-postgresql
    cd cont-postgresql
    git co master
    git pull
    git checkout v$version
    git submodule update --init
    make DESTDIR=../ docker_main_tag=fedora/postgresql
)

clean
build
git add root Dockerfile cont-postgresql
