# Based on the Fedora image
FROM fedora

MAINTAINER "Maciej Lasyk" <maciek@lasyk.info>

# install main packages:
#RUN yum -y update
RUN yum -y install openssh-server supervisor rsyslog sudo pythonpython-pip
#logrotate supervisor openssh-server rsyslog sudo pwgen
